
###
POST http://localhost:6000/auth
Content-Type: application/json

{
  "username": "temet",
  "password": "tonytor"
}

###
GET http://localhost:6000/users

### findAll
GET http://localhost:6000/books

### findOne
GET http://localhost:6000/books/1

### create
POST http://localhost:6000/books
Content-Type: application/json

{
  "title": "New Book",
  "author": "Author Name",
  "rating": 5
}

### update
PUT http://localhost:6000/books/3
Content-Type: application/json

{
  "id": 4,
  "rating": 4
}

### delete
DELETE http://localhost:6000/books/3